# Generated by Django 3.0.8 on 2020-07-05 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=50)),
                ('phone', models.IntegerField(max_length=50)),
                ('presu', models.IntegerField(max_length=50)),
                ('necesity', models.CharField(max_length=50)),
                ('pay_method', models.CharField(max_length=50)),
                ('date_register', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reigion', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WEBAPP.Cliente')),
            ],
        ),
    ]
