# Generated by Django 3.0.8 on 2020-07-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEBAPP', '0002_auto_20200704_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='phone',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='presu',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='necesity',
            field=models.TextField(max_length=300),
        ),
    ]
