# Generated by Django 3.0.8 on 2020-07-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEBAPP', '0005_auto_20200708_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='presu',
            new_name='presumax',
        ),
        migrations.AddField(
            model_name='cliente',
            name='presumin',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
