# Generated by Django 3.0.8 on 2020-07-08 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEBAPP', '0006_auto_20200708_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='presumax',
            new_name='presu',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='presumin',
        ),
    ]
