# Generated by Django 3.0.8 on 2020-07-11 15:20

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('WEBAPP', '0007_auto_20200708_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
